#!/bin/bash
 cypher-shell -u neo4j -p 123456 'LOAD CSV WITH HEADERS FROM "file:///event.csv" AS line CREATE (event:EVENT{e_id:line.e_id, time:line.time, text:line.text});'
 cypher-shell -u neo4j -p 123456 'LOAD CSV WITH HEADERS FROM "file:///location.csv" AS line CREATE (location:LOCATION{l_id:line.l_id, locationName:line.location});'
 cypher-shell -u neo4j -p 123456 'LOAD CSV WITH HEADERS FROM "file:///patient.csv" AS line CREATE (patient:PATIENT{p_id:line.p_id, patientName:line.name, age:line.age,gender:line.gender});'
 cypher-shell -u neo4j -p 123456 'LOAD CSV WITH HEADERS FROM "file:///topic.csv" AS line CREATE (topic:TOPIC{t_id:line.t_id, topicName:line.topic});'
 cypher-shell -u neo4j -p 123456 'LOAD CSV WITH HEADERS FROM "file:///event-location.csv" AS line MATCH (FROM:EVENT{e_id:line.e_id}), (TO:LOCATION{l_id:line.l_id}) MERGE (FROM)-[EVENT_LOCATION: EVENT_LOCATION{type:"happenIn"}]->(TO);'
 cypher-shell -u neo4j -p 123456 'LOAD CSV WITH HEADERS FROM "file:///event-topic.csv" AS line MATCH (FROM:EVENT{e_id:line.e_id}), (TO:TOPIC{t_id:line.t_id}) MERGE (FROM)-[EVENT_TOPIC: EVENT_TOPIC{type:"belong2"}]->(TO);'
 cypher-shell -u neo4j -p 123456 'LOAD CSV WITH HEADERS FROM "file:///patient-event.csv" AS line MATCH (FROM:PATIENT{p_id:line.p_id}), (TO:EVENT{e_id:line.e_id}) MERGE (FROM)-[PATIENT_EVENT: PATIENT_EVENT{type:"hasEvent"}]->(TO);'
 cypher-shell -u neo4j -p 123456 'LOAD CSV WITH HEADERS FROM "file:///patient-location.csv" AS line MATCH (FROM:PATIENT{p_id:line.p_id}), (TO:LOCATION{l_id:line.l_id}) MERGE (FROM)-[PATIENT_LOCATION: PATIENT_LOCATION{type:"diagnosedIn"}]->(TO);'
